# Generated by Django 3.0.2 on 2020-01-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_permanent_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alumni_user',
            managers=[
            ],
        ),
    ]
